package javamweidtest;

import java.awt.Cursor;
import java.util.List;

public class Form1 extends javax.swing.JFrame {

    PKCS11Controller m_Controller;

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        EnableGroup1(false);
        
        String OS = System.getProperty("os.name").toLowerCase();
        
        if (isWindows(OS)) {
                m_Controller = new PKCS11Controller(System.getProperty("user.dir")+"\\beidpkcs11.dll");
        } else if (isUnix(OS)) {
                m_Controller = new PKCS11Controller(System.getProperty("user.dir")+"/libbeidpkcs11.so");  //linux
        } else {
                System.out.println("Your OS is not supported!!");
                System.exit(-1);
        }
        m_Controller.SetIssuerCertificate("CA SINPE - PERSONA FISICA.cer");
    }
    
	private boolean isWindows(String OS) {
 
		return (OS.indexOf("win") >= 0);
 
	}
 
	private boolean isUnix(String OS) {
 
		return (OS.indexOf("nix") >= 0 || OS.indexOf("nux") >= 0 || OS.indexOf("aix") > 0 );
 
	}
     
//	private boolean isMac(String OS) {
// 
//		return (OS.indexOf("mac") >= 0);
// 
//	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbNumeroTarjeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxCardReaders = new javax.swing.JComboBox();
        btnLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbCardInfo = new javax.swing.JTextArea();
        tbPassword = new javax.swing.JPasswordField();
        chkMostrar = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnAutenticar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTextoAFirmar = new javax.swing.JTextArea();
        btnFirmar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbTextFirmado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        statusStrip1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JAVA, BEID, ASE -  Firma Digital PKCS#11 Test");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("1. Configuración"));

        jLabel1.setText("Card Reader");

        jLabel3.setText("PIN");

        jLabel5.setText("Número de Tarjeta");

        cbxCardReaders.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCardReadersItemStateChanged(evt);
            }
        });
        cbxCardReaders.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxCardReadersPropertyChange(evt);
            }
        });

        btnLogin.setText("Validar PIN");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
        });

        jLabel7.setText("Card  Info");

        tbCardInfo.setEditable(false);
        tbCardInfo.setColumns(20);
        tbCardInfo.setRows(5);
        jScrollPane4.setViewportView(tbCardInfo);

        tbPassword.setName(""); // NOI18N

        chkMostrar.setText("Mostrar");
        chkMostrar.setEnabled(false);
        chkMostrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkMostrarItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(jLabel1)
                        .add(35, 35, 35)
                        .add(cbxCardReaders, 0, 296, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(tbNumeroTarjeta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(tbPassword)
                                .add(18, 18, 18)
                                .add(chkMostrar)))
                        .add(18, 18, 18)
                        .add(btnLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(33, 33, 33)
                .add(jLabel7)
                .add(311, 311, 311))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(497, Short.MAX_VALUE)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 348, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(20, 20, 20)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(cbxCardReaders, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(tbPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(chkMostrar))
                        .add(32, 32, 32)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(tbNumeroTarjeta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(btnLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(24, 24, 24))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(21, 21, 21)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("2. PKCS#11 - Autenticación"));
        jPanel2.setEnabled(false);

        btnAutenticar.setText("Autenticar");
        btnAutenticar.setEnabled(false);
        btnAutenticar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAutenticarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAutenticarMousePressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(btnAutenticar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(745, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(btnAutenticar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("3. PKCS#11 - Firma"));
        jPanel3.setEnabled(false);

        tbTextoAFirmar.setColumns(20);
        tbTextoAFirmar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        tbTextoAFirmar.setRows(5);
        tbTextoAFirmar.setText(" * This is free software; you can redistribute it and/or modify it\n * under the terms of the GNU Lesser General Public License version\n * 3.0 as published by the Free Software Foundation.\n0A5400120C1A7130\n0A5400120B1A7130");
        tbTextoAFirmar.setEnabled(false);
        jScrollPane3.setViewportView(tbTextoAFirmar);

        btnFirmar.setText("Firmar");
        btnFirmar.setEnabled(false);
        btnFirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFirmarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFirmarMousePressed(evt);
            }
        });

        tbTextFirmado.setEditable(false);
        tbTextFirmado.setColumns(5);
        tbTextFirmado.setRows(5);
        tbTextFirmado.setEnabled(false);
        jScrollPane5.setViewportView(tbTextFirmado);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 349, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnFirmar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 349, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(75, 75, 75)
                        .add(btnFirmar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusStrip1.setText("Cargando Libreria:   beidpkcs11.dll.....");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(statusStrip1)
                .addContainerGap(630, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, statusStrip1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        EnableGroup1(false);
        tbCardInfo.setText("");
        this.setCursor(Cursor.WAIT_CURSOR);
        try {
            if (cbxCardReaders.getSelectedIndex() != 0) {
                int slotIndex = (cbxCardReaders.getSelectedIndex() - 1);
                statusStrip1.setText("Slot Seleccionado[" + slotIndex + "]");
                if ("".equals(new String(tbPassword.getPassword() ))) {
                    String msg = "El Número de PIN es requerido";
                    statusStrip1.setText(msg);
                    return;
                }
                if ("".equals(tbNumeroTarjeta.getText().trim())) {
                    String msg = "El Número de Tarjeta es requerido";
                    statusStrip1.setText(msg);
                    return;
                }

                if (!m_Controller.Login(slotIndex, new String(tbPassword.getPassword() ))) {
                    String msg = "PIN Incorrecto";
                    statusStrip1.setText(msg);
                    return;
                } else {
                    String msg = "PIN Correcto";
                    statusStrip1.setText(msg);

                    if (!m_Controller.NumeroTarjetaValida(slotIndex, tbNumeroTarjeta.getText().trim())) {
                        msg = "Debe proveer un Número de Tarjeta Válido";
                        statusStrip1.setText(msg);
                        return;
                    }
                    EnableGroup2(true);
                    tbCardInfo.setText(m_Controller.GetTokenInfo(slotIndex));
                }

            } else {
                String msg = "Debe Seleccionar un Card Reader";
                statusStrip1.setText(msg);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
            statusStrip1.setText("Ha ocurrido un error: "+ex.getMessage());
        }
        finally {
            EnableGroup1(true);
            this.setCursor(Cursor.DEFAULT_CURSOR);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnAutenticarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutenticarMouseClicked

        btnAutenticar.setEnabled( false);
        this.setCursor(Cursor.WAIT_CURSOR);
        try
        {
            if (cbxCardReaders.getSelectedIndex() != 0) {
                
                StringBuilder error = new StringBuilder ();
                int slotIndex = (cbxCardReaders.getSelectedIndex() - 1);
                if (!m_Controller.Autenticar(slotIndex, new String(tbPassword.getPassword() ), error))
                {
                    statusStrip1.setText(error.toString());
                }
                else
                {
                    String msg = "Autenticación Exitosa";
                    statusStrip1.setText(msg);
                    EnableGroup3(true);
                }
            }
            else
            {
                String msg = "Debe Seleccionar un Card Reader";
                statusStrip1.setText(msg);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
            statusStrip1.setText("Ha ocurrido un error: "+ex.getMessage());
        }            
        finally
        {
            btnAutenticar.setEnabled( true);
            this.setCursor(Cursor.DEFAULT_CURSOR);
        }
    }//GEN-LAST:event_btnAutenticarMouseClicked

    private void btnFirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirmarMouseClicked
        
        btnFirmar.setEnabled(false);
        this.setCursor(Cursor.WAIT_CURSOR);
        try
        {
            if (cbxCardReaders.getSelectedIndex() != 0) {
                EncryptedData encryptedData = new EncryptedData();
                int slotIndex = (cbxCardReaders.getSelectedIndex() - 1);
                byte[] textoaFirmar = tbTextoAFirmar.getText().getBytes("UTF-8");
                if (!m_Controller.Firmar(slotIndex,new String(tbPassword.getPassword() ), textoaFirmar , encryptedData))
                {
                    String msg = "PIN Incorrecto";
                    statusStrip1.setText(msg);
                }
                else
                {
                    tbTextFirmado.setText(encryptedData.ToString());
                    statusStrip1.setText("Texto Firmado Correctamente");
                }
            }
            else
            {
                String msg = "Debe Seleccionar un Card Reader";
                statusStrip1.setText(msg);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
            statusStrip1.setText("Ha ocurrido un error: "+ex.getMessage());
        }
        finally
        {
            btnFirmar.setEnabled(true);
            this.setCursor(Cursor.DEFAULT_CURSOR);
        }
    }//GEN-LAST:event_btnFirmarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setCursor(Cursor.WAIT_CURSOR);
        try {
            List<String> readers = m_Controller.GetReadersList(false);
            if (readers.size() > 0) {
                cbxCardReaders.addItem("[Selecccione un Card Reader]");
                cbxCardReaders.setSelectedIndex(0);
                for (String reader : readers) {
                    cbxCardReaders.addItem(reader);
                }
                statusStrip1.setText("Card Readers Cargados.");
                EnableGroup1(true);
            } else {
                statusStrip1.setText("No se detectaron Card Readers.");
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
            statusStrip1.setText("Ha ocurrido un error: "+ex.getMessage());
        }    
        finally {
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }
    }//GEN-LAST:event_formWindowOpened
    private void cbxCardReadersPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxCardReadersPropertyChange
    }//GEN-LAST:event_cbxCardReadersPropertyChange

    private void cbxCardReadersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCardReadersItemStateChanged
        EnableGroup2(false);
        EnableGroup3(false);
        statusStrip1.setText("Card Readers Cargados.");
        tbPassword.setText("");
        tbNumeroTarjeta.setText("");
        tbCardInfo.setText("");
        tbTextFirmado.setText("");
    }//GEN-LAST:event_cbxCardReadersItemStateChanged

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
        statusStrip1.setText("Validando.");
    }//GEN-LAST:event_btnLoginMousePressed

    private void btnAutenticarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutenticarMousePressed
        statusStrip1.setText("Autenticando con servidor OCSP.");
    }//GEN-LAST:event_btnAutenticarMousePressed

    private void btnFirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirmarMousePressed
        statusStrip1.setText("Firmando.");
    }//GEN-LAST:event_btnFirmarMousePressed

    private void chkMostrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkMostrarItemStateChanged
        if(chkMostrar.isSelected()) {
            tbPassword.setEchoChar((char)0);
        }
        else {
            tbPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkMostrarItemStateChanged

    private void EnableGroup1(boolean enabled) {
        jPanel1.setEnabled(enabled);
        cbxCardReaders.setEnabled(enabled);
        tbPassword.setEnabled(enabled);
        tbNumeroTarjeta.setEnabled(enabled);
        tbCardInfo.setEnabled(enabled);
        btnLogin.setEnabled(enabled);
        chkMostrar.setEnabled(enabled);
    }

    private void EnableGroup2(boolean enabled) {
        jPanel2.setEnabled(enabled);
        btnAutenticar.setEnabled(enabled);
    }

    private void EnableGroup3(boolean enabled) {

        jPanel2.setEnabled(enabled);
        tbTextoAFirmar.setEnabled(enabled);
        tbTextFirmado.setEnabled(enabled);
        btnFirmar.setEnabled(enabled);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels = javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx = 0; idx < installedLookAndFeels.length; idx++) {
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutenticar;
    private javax.swing.JButton btnFirmar;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxCardReaders;
    private javax.swing.JCheckBox chkMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel statusStrip1;
    private javax.swing.JTextArea tbCardInfo;
    private javax.swing.JTextField tbNumeroTarjeta;
    private javax.swing.JPasswordField tbPassword;
    private javax.swing.JTextArea tbTextFirmado;
    private javax.swing.JTextArea tbTextoAFirmar;
    // End of variables declaration//GEN-END:variables
}
