CURRENTDIR=`pwd`
JAREXECFILE=$CURRENTDIR/JAVAmwEIDTest.jar
LIBRARY=$CURRENTDIR/lib/
echo $JAREXECFILE
echo $LIBRARY
export LD_LIBRARY_PATH=$LIBRARY
java -jar $JAREXECFILE -Djava.library.path=$LIBRARY 
